/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Controller.Controller;
import deepspace.EnemyToUI;

public class EnemyView extends javax.swing.JPanel {
    
    LootView lootView;
    DamageView damageView;
    
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
        
        lootView = new LootView();
        panelLoot.add(lootView);
        damageView = new DamageView();
        panelPerdidas.add(damageView);
        
        repaint();
        revalidate();
    }
    
    public void setEnemyView(EnemyToUI e){
        name.setText(e.getName());
        ammoPower.setText(Float.toString(e.getAmmoPower()));
        shieldPower.setText(Float.toString(e.getShieldPower()));
        
        lootView.setLootView(e.getLoot());
        damageView.setDamageView(e.getDamage());
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ammoPower = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shieldPower = new javax.swing.JLabel();
        panelLoot = new javax.swing.JPanel();
        panelPerdidas = new javax.swing.JPanel();

        jLabel1.setText("Enemigo:");

        name.setText("jLabel2");

        jLabel3.setText("Potencia de fuego:");

        ammoPower.setText("jLabel4");

        jLabel5.setText("Potencia de defensa:");

        shieldPower.setText("jLabel6");

        panelLoot.setBorder(javax.swing.BorderFactory.createTitledBorder("Botin"));

        panelPerdidas.setBorder(javax.swing.BorderFactory.createTitledBorder("Perdidas"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPerdidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(ammoPower)
                            .addComponent(shieldPower))
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addComponent(panelLoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ammoPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shieldPower))
                .addGap(18, 18, 18)
                .addComponent(panelLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammoPower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panelLoot;
    private javax.swing.JPanel panelPerdidas;
    private javax.swing.JLabel shieldPower;
    // End of variables declaration//GEN-END:variables
}
